--------------------------------------------------------
-- Archivo creado  - sábado-mayo-21-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CUSTOMERS_ID_GENERATE
--------------------------------------------------------

DROP TABLE CUSTOMER;
DROP TABLE EMPLOYEE;
DROP TABLE INVOICE;
DROP TABLE PRODUCT;
DROP TABLE RELEASE_ORDER;
DROP TABLE ROLE;
DROP TABLE SALE;
DROP TABLE SERVICE;
DROP TABLE STATE_RELEASE_ORDER;
DROP TABLE STATE_SERVICE;

drop SEQUENCE CUSTOMER_ID_GENERATE;
drop SEQUENCE EMPLOYEE_ID_GENERATE;
drop SEQUENCE INVOICE_ID_GENERATE;
drop SEQUENCE PRODUCT_ID_GENERATE;
drop SEQUENCE RELEASE_ORDER_ID_GENERATE;
drop SEQUENCE ROLE_ID_GENERATE;
drop SEQUENCE SALE_ID_GENERATE;
drop SEQUENCE SERVICE_ID_GENERATE;

   CREATE SEQUENCE  "BUENOSAIRES"."CUSTOMER_ID_GENERATE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 10 START WITH 10 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
-------------------------------------------------------
--  DDL for Sequence EMPLOYEE_ID_GENERATE
--------------------------------------------------------

   CREATE SEQUENCE  "BUENOSAIRES"."EMPLOYEE_ID_GENERATE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 10 START WITH 10 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INVOICE_ID_GENERATE
--------------------------------------------------------

   CREATE SEQUENCE  "BUENOSAIRES"."INVOICE_ID_GENERATE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 10 START WITH 10 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PRODUCT_ID_GENERATE
--------------------------------------------------------

   CREATE SEQUENCE  "BUENOSAIRES"."PRODUCT_ID_GENERATE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 10 START WITH 10 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence RELEASE_ORDER_ID_GENERATE
--------------------------------------------------------

   CREATE SEQUENCE  "BUENOSAIRES"."RELEASE_ORDER_ID_GENERATE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 10 START WITH 10 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ROLE_ID_GENERATE
--------------------------------------------------------

   CREATE SEQUENCE  "BUENOSAIRES"."ROLE_ID_GENERATE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 10 START WITH 10 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SALE_ID_GENERATE
--------------------------------------------------------

   CREATE SEQUENCE  "BUENOSAIRES"."SALE_ID_GENERATE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 10 START WITH 10 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SERVICE_ID_GENERATE
--------------------------------------------------------

   CREATE SEQUENCE  "BUENOSAIRES"."SERVICE_ID_GENERATE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 10 START WITH 10 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "BUENOSAIRES"."CUSTOMER" 
   (	"ID_CUSTOMER" VARCHAR2(20 BYTE), 
	"NAME_CUSTOMER" VARCHAR2(60 BYTE), 
	"LASTNAME_CUSTOMER" VARCHAR2(60 BYTE), 
	"PASSWORD_CUSTOMER" VARCHAR2(20 BYTE), 
	"REPEATPASSWORD_CUSTOMER" VARCHAR2(20 BYTE), 
	"RUT_CUSTOMER" VARCHAR2(15 BYTE), 
	"EMAIL_CUSTOMER" VARCHAR2(60 BYTE), 
	"ADRESS_CUSTOMER" VARCHAR2(100 BYTE), 
	"IS_AUTHENTICATE" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"IS_ONLINE" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "BUENOSAIRES"."EMPLOYEE" 
   (	"ID_EMPLOYEE" VARCHAR2(20 BYTE), 
	"NAME_EMPLOYEE" VARCHAR2(60 BYTE), 
	"LASTNAME_EMPLOYEE" VARCHAR2(60 BYTE), 
	"RUT_EMPLOYEE" VARCHAR2(20 BYTE), 
	"ADRESS_EMPLOYEE" VARCHAR2(100 BYTE), 
	"EMAIL_EMPLOYEE" VARCHAR2(100 BYTE), 
	"PASSWOORD_EMPLOYEE" VARCHAR2(20 BYTE), 
	"REPEATPASSWORD_EMPLOYEE" VARCHAR2(20 BYTE), 
	"IS_AUTHENTICATE" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"IS_ONLINE" VARCHAR2(1 BYTE), 
	"ID_ROLE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVOICE
--------------------------------------------------------

  CREATE TABLE "BUENOSAIRES"."INVOICE" 
   (	"ID_INVOICE" VARCHAR2(20 BYTE), 
	"ID_CUSTOMER" VARCHAR2(20 BYTE), 
	"DATE_INVOICE" VARCHAR2(20 BYTE), 
	"DESCRIPTION_INVOICE" VARCHAR2(500 BYTE), 
	"ID_SELL" VARCHAR2(20 BYTE), 
	"ID_RELEASE_ORDER" VARCHAR2(20 BYTE), 
	"ID_PRODUCT" NUMBER(*,0), 
	"ID_SERVICE" VARCHAR2(20 BYTE), 
	"AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "BUENOSAIRES"."PRODUCT" 
   (	"ID" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"VALUE" VARCHAR2(10 BYTE), 
	"MARK" VARCHAR2(40 BYTE), 
	"IS_AVAILABLE" VARCHAR2(1 BYTE), 
	"IMAGE_01" LONG RAW, 
	"IS_OFERT" VARCHAR2(1 BYTE), 
	"MODEL" VARCHAR2(100 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RELEASE_ORDER
--------------------------------------------------------

  CREATE TABLE "BUENOSAIRES"."RELEASE_ORDER" 
   (	"ID_RELEASE_ORDER" VARCHAR2(20 BYTE), 
	"ID_CUSTOMER" VARCHAR2(20 BYTE), 
	"ID_STATE" VARCHAR2(2 BYTE), 
	"ID_PRODUCT" VARCHAR2(20 BYTE), 
	"ID_SELL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "BUENOSAIRES"."ROLE" 
   (	"ID_ROLE" VARCHAR2(20 BYTE), 
	"NAME_ROLE" VARCHAR2(100 BYTE), 
	"DESCRIPTION_ROLE" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALE
--------------------------------------------------------

  CREATE TABLE "BUENOSAIRES"."SALE" 
   (	"ID_SALE" VARCHAR2(20 BYTE), 
	"DESCRIPTION_SALE" VARCHAR2(20 BYTE), 
	"ID_CUSTOMER" VARCHAR2(20 BYTE), 
	"ID_PRODUCT" VARCHAR2(20 BYTE), 
	"ID_EMPLOYEE" VARCHAR2(20 BYTE), 
	"ID_SERVICE" VARCHAR2(20 BYTE), 
	"IS_PAY" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICE
--------------------------------------------------------

  CREATE TABLE "BUENOSAIRES"."SERVICE" 
   (	"ID_SERVICE" VARCHAR2(20 BYTE), 
	"DESCRIPTION_SERVICE" VARCHAR2(500 BYTE), 
	"PRICE_SERVICE" VARCHAR2(20 BYTE), 
	"ID_EMPLOYEE" VARCHAR2(20 BYTE), 
	"ID_CUSTOMER" VARCHAR2(20 BYTE), 
	"DATE_SERVICE" VARCHAR2(20 BYTE), 
	"HOUR_SERVICE" VARCHAR2(20 BYTE), 
	"ID_STATE" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATE_RELEASE_ORDER
--------------------------------------------------------

  CREATE TABLE "BUENOSAIRES"."STATE_RELEASE_ORDER" 
   (	"ID_STATE_RELEASE_ORDER" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATE_SERVICE
--------------------------------------------------------

  CREATE TABLE "BUENOSAIRES"."STATE_SERVICE" 
   (	"ID_STATE_SERVICE" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BUENOSAIRES.CUSTOMER
SET DEFINE OFF;

Insert into BUENOSAIRES.CUSTOMER (ID_CUSTOMER,NAME_CUSTOMER,LASTNAME_CUSTOMER,PASSWORD_CUSTOMER,REPEATPASSWORD_CUSTOMER,RUT_CUSTOMER,EMAIL_CUSTOMER,ADRESS_CUSTOMER,IS_AUTHENTICATE,IS_ONLINE) values (CUSTOMER_ID_GENERATE.NEXTVAL,'Alejandro','Magno','tuconquer','tuconquer','11.111.111-1','tuconquer@roma.rm','roma 1, Roma','N','N');
Insert into BUENOSAIRES.CUSTOMER (ID_CUSTOMER,NAME_CUSTOMER,LASTNAME_CUSTOMER,PASSWORD_CUSTOMER,REPEATPASSWORD_CUSTOMER,RUT_CUSTOMER,EMAIL_CUSTOMER,ADRESS_CUSTOMER,IS_AUTHENTICATE,IS_ONLINE) values (CUSTOMER_ID_GENERATE.NEXTVAL,'Maximo','Decimo Meridio','tugladiator','tugladiator','22.222.222-2','tugladiator@roma.rm','coliseo 1, Roma','N','N');
Insert into BUENOSAIRES.CUSTOMER (ID_CUSTOMER,NAME_CUSTOMER,LASTNAME_CUSTOMER,PASSWORD_CUSTOMER,REPEATPASSWORD_CUSTOMER,RUT_CUSTOMER,EMAIL_CUSTOMER,ADRESS_CUSTOMER,IS_AUTHENTICATE,IS_ONLINE) values (CUSTOMER_ID_GENERATE.NEXTVAL,'Onur','Segit','tuconquer','tuconquer','33.333.333-3','tugladiator@turquia.tk','motel 1, Turquía','N','N');
Insert into BUENOSAIRES.CUSTOMER (ID_CUSTOMER,NAME_CUSTOMER,LASTNAME_CUSTOMER,PASSWORD_CUSTOMER,REPEATPASSWORD_CUSTOMER,RUT_CUSTOMER,EMAIL_CUSTOMER,ADRESS_CUSTOMER,IS_AUTHENTICATE,IS_ONLINE) values (CUSTOMER_ID_GENERATE.NEXTVAL,'Sultán','Suleiman','tusultan','tusultan','44.555.555-5','tusultar@turquia.tk','motel 2, Turquía','N','N');
REM INSERTING into BUENOSAIRES.EMPLOYEE
SET DEFINE OFF;

Insert into BUENOSAIRES.EMPLOYEE (ID_EMPLOYEE,NAME_EMPLOYEE,LASTNAME_EMPLOYEE,RUT_EMPLOYEE,ADRESS_EMPLOYEE,EMAIL_EMPLOYEE,PASSWOORD_EMPLOYEE,REPEATPASSWORD_EMPLOYEE,IS_AUTHENTICATE,IS_ONLINE,ID_ROLE) values (EMPLOYEE_ID_GENERATE.NEXTVAL,'carlos','salgado','1.000.000-0','c.salg@ba.com','avenida falsa 123','employee','employee','N','N','1');
Insert into BUENOSAIRES.EMPLOYEE (ID_EMPLOYEE,NAME_EMPLOYEE,LASTNAME_EMPLOYEE,RUT_EMPLOYEE,ADRESS_EMPLOYEE,EMAIL_EMPLOYEE,PASSWOORD_EMPLOYEE,REPEATPASSWORD_EMPLOYEE,IS_AUTHENTICATE,IS_ONLINE,ID_ROLE) values (EMPLOYEE_ID_GENERATE.NEXTVAL,'Steve','Rogger','2.000.000','st.rogger@ba.com','brooklyn , calle random 123  ','employee','employee','N','N','3');
Insert into BUENOSAIRES.EMPLOYEE (ID_EMPLOYEE,NAME_EMPLOYEE,LASTNAME_EMPLOYEE,RUT_EMPLOYEE,ADRESS_EMPLOYEE,EMAIL_EMPLOYEE,PASSWOORD_EMPLOYEE,REPEATPASSWORD_EMPLOYEE,IS_AUTHENTICATE,IS_ONLINE,ID_ROLE) values (EMPLOYEE_ID_GENERATE.NEXTVAL,'Tony','Stark','3.000.000-0','tony.stark@ba.com','Malibú California , calle random 123  ','employee','employee','N','N','2');
Insert into BUENOSAIRES.EMPLOYEE (ID_EMPLOYEE,NAME_EMPLOYEE,LASTNAME_EMPLOYEE,RUT_EMPLOYEE,ADRESS_EMPLOYEE,EMAIL_EMPLOYEE,PASSWOORD_EMPLOYEE,REPEATPASSWORD_EMPLOYEE,IS_AUTHENTICATE,IS_ONLINE,ID_ROLE) values (EMPLOYEE_ID_GENERATE.NEXTVAL,'Natasha','Romanov','4.000.000-0','nat.romanov@ba.com','desconoocido','employee','employee','N','N','4');
REM INSERTING into BUENOSAIRES.INVOICE
SET DEFINE OFF;

Insert into BUENOSAIRES.INVOICE (ID_INVOICE,ID_CUSTOMER,DATE_INVOICE,DESCRIPTION_INVOICE,ID_SELL,ID_RELEASE_ORDER,ID_PRODUCT,ID_SERVICE,AMOUNT) 
values (INVOICE_ID_GENERATE.NEXTVAL,'10','19/05/2022','cualquiera de calor hermano','10','10','10','10','600000');
Insert into BUENOSAIRES.INVOICE (ID_INVOICE,ID_CUSTOMER,DATE_INVOICE,DESCRIPTION_INVOICE,ID_SELL,ID_RELEASE_ORDER,ID_PRODUCT,ID_SERVICE,AMOUNT) 
values (INVOICE_ID_GENERATE.NEXTVAL,'20','19/05/2022','cualquiera de calor y sed hermano','20','20','20','20','500000');
REM INSERTING into BUENOSAIRES.PRODUCT
SET DEFINE OFF;

Insert into BUENOSAIRES.PRODUCT (ID,NAME,VALUE,MARK,IS_AVAILABLE,IMAGE_01,IS_OFERT,MODEL,CATEGORY,DESCRIPTION) values (PRODUCT_ID_GENERATE.NEXTVAL,'aire acondicionado 12000btu','650000','Mademsa','S',null,'N','INDOR LONG SLEEP SILENT','AIRES_ACONDICIONADO','frío como tu ex profesor de calculo');
Insert into BUENOSAIRES.PRODUCT (ID,NAME,VALUE,MARK,IS_AVAILABLE,IMAGE_01,IS_OFERT,MODEL,CATEGORY,DESCRIPTION) values (PRODUCT_ID_GENERATE.NEXTVAL,'aire acondicionado frio caliente wifi 12000btu','650000','Mademsa','S',null,'N','INDOR LONG SLEEP SILENT','AIRES_ACONDICIONADO','Apto para todo el año');
Insert into BUENOSAIRES.PRODUCT (ID,NAME,VALUE,MARK,IS_AVAILABLE,IMAGE_01,IS_OFERT,MODEL,CATEGORY,DESCRIPTION) values (PRODUCT_ID_GENERATE.NEXTVAL,'aire acondicionado 9000btu','430000','ANWO','S',null,'N','INDOR LONG SLEEP SILENT','AIRES_ACONDICIONADO','frío como tu ex');
REM INSERTING into BUENOSAIRES.RELEASE_ORDER
SET DEFINE OFF;

Insert into BUENOSAIRES.RELEASE_ORDER (ID_RELEASE_ORDER,ID_CUSTOMER,ID_STATE,ID_PRODUCT,ID_SELL) 
values (RELEASE_ORDER_ID_GENERATE.NEXTVAL,'10','4','10','10');
Insert into BUENOSAIRES.RELEASE_ORDER (ID_RELEASE_ORDER,ID_CUSTOMER,ID_STATE,ID_PRODUCT,ID_SELL) 
values (RELEASE_ORDER_ID_GENERATE.NEXTVAL,'20','3','20','20');
REM INSERTING into BUENOSAIRES.ROLE
SET DEFINE OFF;

Insert into BUENOSAIRES.ROLE (ID_ROLE,NAME_ROLE,DESCRIPTION_ROLE) values ('1','vendedor','persona que vende aires en tienda fÍsica ');
Insert into BUENOSAIRES.ROLE (ID_ROLE,NAME_ROLE,DESCRIPTION_ROLE) values ('2','tecnico','personal especializado de la empresa en instalar aires acondicionados ');
Insert into BUENOSAIRES.ROLE (ID_ROLE,NAME_ROLE,DESCRIPTION_ROLE) values ('3','bodeguero','personal encargada de administrar la bodega de buenos aires');
Insert into BUENOSAIRES.ROLE (ID_ROLE,NAME_ROLE,DESCRIPTION_ROLE) values ('4','administrador','persona encargada de administrar la tienda');
REM INSERTING into BUENOSAIRES.SALE
SET DEFINE OFF;

Insert into BUENOSAIRES.SALE (ID_SALE,DESCRIPTION_SALE,ID_CUSTOMER,ID_PRODUCT,ID_EMPLOYEE,ID_SERVICE,IS_PAY) 
values (SALE_ID_GENERATE.NEXTVAL,'venta oline','20','10','10','10','Y');
Insert into BUENOSAIRES.SALE (ID_SALE,DESCRIPTION_SALE,ID_CUSTOMER,ID_PRODUCT,ID_EMPLOYEE,ID_SERVICE,IS_PAY) 
values (SALE_ID_GENERATE.NEXTVAL,'venta oline','40','20','10','20','Y');
REM INSERTING into BUENOSAIRES.SERVICE
SET DEFINE OFF;

Insert into BUENOSAIRES.SERVICE (ID_SERVICE,DESCRIPTION_SERVICE,PRICE_SERVICE,ID_EMPLOYEE,ID_CUSTOMER,DATE_SERVICE,HOUR_SERVICE,ID_STATE) 
values (SERVICE_ID_GENERATE.NEXTVAL,'instalacion de aire acondicionado piso 1','250000','10','10','05/30/22','15:00','1');
Insert into BUENOSAIRES.SERVICE (ID_SERVICE,DESCRIPTION_SERVICE,PRICE_SERVICE,ID_EMPLOYEE,ID_CUSTOMER,DATE_SERVICE,HOUR_SERVICE,ID_STATE) 
values (SERVICE_ID_GENERATE.NEXTVAL,'instalacion de aire acondicionado casa','350000','10','20','05/20/22','18:00','2');
REM INSERTING into BUENOSAIRES.STATE_RELEASE_ORDER
SET DEFINE OFF;

Insert into BUENOSAIRES.STATE_RELEASE_ORDER (ID_STATE_RELEASE_ORDER,STATE) values ('1','no aplica');
Insert into BUENOSAIRES.STATE_RELEASE_ORDER (ID_STATE_RELEASE_ORDER,STATE) values ('2','en bodega');
Insert into BUENOSAIRES.STATE_RELEASE_ORDER (ID_STATE_RELEASE_ORDER,STATE) values ('3','despachado');
Insert into BUENOSAIRES.STATE_RELEASE_ORDER (ID_STATE_RELEASE_ORDER,STATE) values ('4','entregado');
REM INSERTING into BUENOSAIRES.STATE_SERVICE
SET DEFINE OFF;

Insert into BUENOSAIRES.STATE_SERVICE (ID_STATE_SERVICE,STATE) values ('1','aceptado');
Insert into BUENOSAIRES.STATE_SERVICE (ID_STATE_SERVICE,STATE) values ('2','modificado');
Insert into BUENOSAIRES.STATE_SERVICE (ID_STATE_SERVICE,STATE) values ('3','cerrado');
--------------------------------------------------------
--  DDL for Index INVOICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUENOSAIRES"."INVOICE_PK" ON "BUENOSAIRES"."INVOICE" ("ID_INVOICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RELEASE_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUENOSAIRES"."RELEASE_ORDER_PK" ON "BUENOSAIRES"."RELEASE_ORDER" ("ID_RELEASE_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUENOSAIRES"."ROLE_PK" ON "BUENOSAIRES"."ROLE" ("ID_ROLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SALE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUENOSAIRES"."SALE_PK" ON "BUENOSAIRES"."SALE" ("ID_SALE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SELLER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUENOSAIRES"."SELLER_PK" ON "BUENOSAIRES"."EMPLOYEE" ("ID_EMPLOYEE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STATE_RELEASE_ORDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUENOSAIRES"."STATE_RELEASE_ORDER_PK" ON "BUENOSAIRES"."STATE_RELEASE_ORDER" ("ID_STATE_RELEASE_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STATE_SERVICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUENOSAIRES"."STATE_SERVICE_PK" ON "BUENOSAIRES"."STATE_SERVICE" ("ID_STATE_SERVICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUENOSAIRES"."TABLE1_PK" ON "BUENOSAIRES"."PRODUCT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUENOSAIRES"."USERS_PK" ON "BUENOSAIRES"."CUSTOMER" ("ID_CUSTOMER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table INVOICE
--------------------------------------------------------

  ALTER TABLE "BUENOSAIRES"."INVOICE" MODIFY ("ID_INVOICE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."INVOICE" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."INVOICE" MODIFY ("ID_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."INVOICE" MODIFY ("DATE_INVOICE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."INVOICE" MODIFY ("DESCRIPTION_INVOICE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."INVOICE" MODIFY ("ID_SELL" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."INVOICE" MODIFY ("ID_RELEASE_ORDER" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."INVOICE" MODIFY ("ID_PRODUCT" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."INVOICE" MODIFY ("ID_SERVICE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."INVOICE" ADD CONSTRAINT "INVOICE_PK" PRIMARY KEY ("ID_INVOICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATE_RELEASE_ORDER
--------------------------------------------------------

  ALTER TABLE "BUENOSAIRES"."STATE_RELEASE_ORDER" MODIFY ("ID_STATE_RELEASE_ORDER" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."STATE_RELEASE_ORDER" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."STATE_RELEASE_ORDER" ADD CONSTRAINT "STATE_RELEASE_ORDER_PK" PRIMARY KEY ("ID_STATE_RELEASE_ORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "BUENOSAIRES"."CUSTOMER" MODIFY ("ID_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."CUSTOMER" MODIFY ("NAME_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."CUSTOMER" MODIFY ("LASTNAME_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."CUSTOMER" MODIFY ("PASSWORD_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."CUSTOMER" MODIFY ("REPEATPASSWORD_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."CUSTOMER" MODIFY ("RUT_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."CUSTOMER" MODIFY ("EMAIL_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."CUSTOMER" MODIFY ("ADRESS_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."CUSTOMER" MODIFY ("IS_AUTHENTICATE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."CUSTOMER" MODIFY ("IS_ONLINE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."CUSTOMER" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID_CUSTOMER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATE_SERVICE
--------------------------------------------------------

  ALTER TABLE "BUENOSAIRES"."STATE_SERVICE" MODIFY ("ID_STATE_SERVICE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."STATE_SERVICE" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."STATE_SERVICE" ADD CONSTRAINT "STATE_SERVICE_PK" PRIMARY KEY ("ID_STATE_SERVICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "BUENOSAIRES"."EMPLOYEE" MODIFY ("ID_EMPLOYEE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."EMPLOYEE" MODIFY ("NAME_EMPLOYEE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."EMPLOYEE" MODIFY ("LASTNAME_EMPLOYEE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."EMPLOYEE" MODIFY ("RUT_EMPLOYEE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."EMPLOYEE" MODIFY ("ADRESS_EMPLOYEE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."EMPLOYEE" MODIFY ("EMAIL_EMPLOYEE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."EMPLOYEE" MODIFY ("PASSWOORD_EMPLOYEE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."EMPLOYEE" MODIFY ("REPEATPASSWORD_EMPLOYEE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."EMPLOYEE" MODIFY ("IS_AUTHENTICATE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."EMPLOYEE" MODIFY ("IS_ONLINE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."EMPLOYEE" MODIFY ("ID_ROLE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."EMPLOYEE" ADD CONSTRAINT "SELLER_PK" PRIMARY KEY ("ID_EMPLOYEE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALE
--------------------------------------------------------

  ALTER TABLE "BUENOSAIRES"."SALE" MODIFY ("ID_SALE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."SALE" MODIFY ("DESCRIPTION_SALE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."SALE" MODIFY ("ID_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."SALE" MODIFY ("ID_PRODUCT" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."SALE" MODIFY ("ID_EMPLOYEE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."SALE" MODIFY ("ID_SERVICE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."SALE" ADD CONSTRAINT "SALE_PK" PRIMARY KEY ("ID_SALE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUENOSAIRES"."SALE" MODIFY ("IS_PAY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "BUENOSAIRES"."PRODUCT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."PRODUCT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."PRODUCT" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."PRODUCT" MODIFY ("MARK" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."PRODUCT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."PRODUCT" MODIFY ("IS_AVAILABLE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."PRODUCT" MODIFY ("IS_OFERT" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."PRODUCT" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."PRODUCT" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."PRODUCT" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "BUENOSAIRES"."ROLE" MODIFY ("ID_ROLE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."ROLE" MODIFY ("NAME_ROLE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."ROLE" MODIFY ("DESCRIPTION_ROLE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."ROLE" ADD CONSTRAINT "ROLE_PK" PRIMARY KEY ("ID_ROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RELEASE_ORDER
--------------------------------------------------------

  ALTER TABLE "BUENOSAIRES"."RELEASE_ORDER" MODIFY ("ID_RELEASE_ORDER" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."RELEASE_ORDER" ADD CONSTRAINT "RELEASE_ORDER_PK" PRIMARY KEY ("ID_RELEASE_ORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUENOSAIRES"."RELEASE_ORDER" MODIFY ("ID_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."RELEASE_ORDER" MODIFY ("ID_STATE" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."RELEASE_ORDER" MODIFY ("ID_PRODUCT" NOT NULL ENABLE);
  ALTER TABLE "BUENOSAIRES"."RELEASE_ORDER" MODIFY ("ID_SELL" NOT NULL ENABLE);
